### ISSUE TITLE
About the TDA universe in Julia

### ISSUE THREAD

**Issue by vituri** [tdaverse/tdaverse#3]
Hi!

I am currently writing a "TDA universe" using the Julia language. The main advantage is that it solves the 2-languages problem, so the packages can be 100% written in Julia. Having to use C++ to speed R code is what made me learn Julia in the first place, even with my love for R.

I see you all are writing lots of packages about TDA in R. Are you interested in porting them to Julia? I can always call R from Julia, but writing them 100% in Julia has a lot of advantages.

I already sketched in Julia the Mapper algorithm, the ToMATo algorithm, the Ripser (not really me but the package probably will be in JuliaTDA some day) and I am starting to write code to manipulate simplicial complexes. Take a look, if you wish: 
https://github.com/JuliaTDA
There is also this work-in-progress book:
https://vituri.github.io/TDA_with_julia/

**Comment by corybrunson** [comment]
Hi @vituri ! I apologize for not replying back in November. The collection looks very cool.

Could you explain what it would mean to port the R packages to Julia? You're of course welcome to rewrite the methods in Julia based on their implementations here—i believe all of the source code is open for reuse with attribution. I agree that it makes the most sense to keep the collection self-contained, taking advantage of Julia's strengths.

I've been supervising a project in Julia for a while, but a variety of factors have slowed it, and i haven't really been able to learn the language enough to use it in my day-to-day. So i am not well-positioned to contribute or advise, but certainly i'll help if i can.

**Comment by vituri** [comment]
Hi, @corybrunson ! 

By "port" I really mean "translate to Julia", so the packages will be a 100% Julia implementation. I could just adapt and copy all your code, but if you are willing to contribute to them in Julia, it would be better and I could help. I've been studying Julia for some months now and I believe I can write some packages that will performe reasonably, without need to use C++.

As I see, R/Python users rarely can code in C++, so even people who are interested in TDA (like data scientists and researchers) will be blocked to contribute to the R/Python packages. In Julia this blockage does not exist. 

Besides that, there is a recent movement in creating Organizations to code in Julia (check for example the algebra orgs here https://julialang.org/community/organizations/ ). Being a "scientific" language we can attract more people to contribute. In July I will give a workshop about "TDA using Julia" in the Brazilian Topology Meeting, and maybe I can find some students that are willing to contribute.
